### Tensorflowテスト
https://www.tensorflow.org/tutorials/quickstart/beginner?hl=ja

In [3]:
import tensorflow as tf

In [19]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

print(x_train.shape)  # 28x28サイズ 6000 データ
print(x_train[0].shape)
print(x_train[:1].shape)
#print(x_train[:1])
print(type(x_train))
print(y_train[0])


(60000, 28, 28)
(28, 28)
(1, 28, 28)
<class 'numpy.ndarray'>
5


In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ -7.4069963 ,  -8.097564  ,  -0.04473843,   8.9822445 ,
        -23.52836   ,  13.653843  , -15.141355  ,  -7.0329967 ,
         -8.032912  ,  -4.2502637 ]], dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.14193171, 0.08177402, 0.09653236, 0.07007233, 0.0992381 ,
        0.09862829, 0.11869501, 0.05416759, 0.1021638 , 0.13679683]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

2.3163972

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2979 - accuracy: 0.9135
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1462 - accuracy: 0.9555
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1088 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0913 - accuracy: 0.9717
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0757 - accuracy: 0.9769


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0762 - accuracy: 0.9762 - 830ms/epoch - 3ms/step


[0.07618366181850433, 0.9761999845504761]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.4972516e-08, 1.6737960e-09, 4.1485227e-06, 3.9568878e-04,
        5.7717189e-11, 1.9579234e-06, 2.8053750e-13, 9.9959582e-01,
        3.8980366e-07, 2.0225382e-06],
       [5.0118114e-08, 7.4971782e-04, 9.9887949e-01, 2.9117952e-04,
        1.1193152e-15, 7.9458194e-05, 3.7981942e-09, 4.5899184e-13,
        6.7638403e-08, 1.6391787e-13],
       [1.3775905e-07, 9.9948728e-01, 2.6339119e-05, 4.5446700e-06,
        1.6617119e-05, 1.2450325e-05, 1.6636487e-06, 2.8723653e-04,
        1.6224237e-04, 1.4324190e-06],
       [9.9974185e-01, 4.1516439e-09, 1.8166301e-04, 1.5911403e-06,
        4.6510596e-08, 2.0641316e-06, 1.8474413e-05, 5.0870600e-05,
        4.6958068e-08, 3.3885037e-06],
       [1.4269838e-05, 3.1510108e-10, 2.6674941e-06, 4.9649600e-09,
        9.9836904e-01, 7.4792410e-07, 2.0530376e-06, 3.4631074e-05,
        2.3358771e-07, 1.5762992e-03]], dtype=float32)>